# -*- coding: utf-8 -*-
"""coding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17sUQnqap5Mi8F1y4uMnZGBnn4I35Tbps
"""

a = int(input())
b = int(input())
sum = a + b
print(sum)

a = input()
b = input()
print(b,a)

s = 'This company is not poor at all'
ans = s.replace('not poor at all', 'good')
print(ans)

s = "This company is not poor at all"
r1 = s.replace("not","good")
r2 = r1.replace("at all","")
print(r2)

s = "This company is not poor at all"
r = str.split(s)
r.insert(4,"good")
print(r[0],r[1],r[2],r[4],r[5])

l = set([1, 3, 1, 2, 2, 4, 5, 3])
set1 = (list(l))
set1.reverse()
print(set1)

dicl1 = {1:10, 2:20}
dicl2 = {3:30, 4:40}
dicl3 = {5:50, 6:60}
d = {}
d.update(dicl1)
d.update(dicl2)
d.update(dicl3)
print(d)

d = {"狗":"dog", "貓":"cat", "豬":"hog", "鳥":"bird"}
a = input("輸入要查詢的動物名稱:")
d[a]

def f5(L):
  L.sort()
  return list(set(L[::2]) & set(L[1::2]))
print(f5([1, 3, 1, 2, 2, 4, 5, 3]))

L = [1, 3, 1, 2, 2, 4, 5, 3]
a = {}
for i in L:
  if L.count(i)>0:
   a[i] = L.count(i)
print (a)

L = [1, 3, 1, 2, 2, 4, 5, 3]
set1 = set(L)
dict1 = dict() 
for e in set1:
  count = 0
  for mat in L:
    if mat == e:
      count +=1
  dict1[e] = count 
print (dict1)

def add (num):
  num1 = 0
  for i in num:
    num1 = num1 + i
  return num1
print(add((10,20,30,40,50,60,70,80,90,100,110,120,130,140,150)))

def textcount(w):
    text = {}
    for c in w:
       text[c] = w.count(c)
    return text
word = "Tetris is a game about making lines. Blocks fall from the top of the screen. They fall one at a time. The player moves the blocks. Once the blocks hit the bottom, they are locked in place. Players try to make lines go across the screen with no gaps. Complete lines disappear. This gives players more room. The blocks pile up during the game. The game ends when the blocks get to the top of the screen."
low = word.lower()
lol = low.replace(" ","")
loll = lol.replace(',',"")
lolll = loll.replace(".","")
textcount(lolll)

def spa(x,y):
    while  y:
        (x, y) = (y, x % y)
    return x
num1 = (spa(10,15))
num2 = (spa(10,12))
if num1 > num2:
  print(num1,">",num2)
else:
  print(num2,">",num1)